### ISSUE TITLE
Feature request: use environment variables in sync path

### ISSUE THREAD

**Issue by QiangF** [Jwink3101/PyFiSync#4]
Just replace pathB with

    os.path.expandvars(path)

**Comment by Jwink3101** [comment]
The beauty of an evaluated python-based config is that you don’t need this feature. Just do

     import os
     pathB = os.path.expandvars('whatever')

**Comment by QiangF** [comment]
Where should I put this modification?
Maybe  make this default, since it doesn't change the original behavior.

**Comment by QiangF** [comment]
Is this he right place?

        config = utils.configparser(sync_dir=path)
        config.pathB = os.path.expandvars(config.pathB)

**Comment by Jwink3101** [comment]
You’d do it in the config file as per my example I included. 

I do not want to make it the default as it is better to be explicit and have you do it. Especially since it is so easy and minor to include in your config.

**Comment by QiangF** [comment]
Oh, you mean the config file is python script?

**Comment by QiangF** [comment]
If so, maybe rename it to config.py.

**Comment by Jwink3101** [comment]
Yes! As stated in the config file template, it is evaluated as a python script
